export enum ProductType {
    FACEBOOK_PROFILE = 'FACEBOOK_PROFILE',
    FACEBOOK_ADS_ACCOUNT = 'FACEBOOK_ADS_ACCOUNT',
    FACEBOOK_PAGES = 'FACEBOOK_PAGES',
    FACEBOOK_BUSINESS_ACCOUNT = 'FACEBOOK_BUSINESS_ACCOUNT',
  }